window.BIRTHDAY_PHOTOS = [
  { src: "photos/01-formal.jpg", caption: "The night we showed up looking like a movie" },
  { src: "photos/02-festival.jpg", caption: "Hanfu, a cloud, and let’s go to Jiangsu" },
  { src: "photos/03-hanfu.jpg", caption: "Fans out. Colors loud. You in the middle of it." },
  { src: "videos/clip-1.mp4", poster: "videos/clip-1.jpg", caption: "iSMART, stickers, and us being so unserious", type: "video" },
  { src: "photos/04-studio.png", caption: "You at the mic. That’s your stage." },
  { src: "photos/05-mics.png", caption: "Two mics. One script. Us, hosting." },
  { src: "videos/clip-2.mp4", poster: "videos/clip-2.jpg", caption: "Just you. The whole room went quiet.", type: "video" },
  { src: "photos/06-stage.jpg", caption: "Purple fits, red curtains, and that song" },
  { src: "photos/07-funny.jpg", caption: "Box heads, bubble wrap, and zero chill" },
  { src: "videos/clip-3.mp4", poster: "videos/clip-3.jpg", caption: "That smile. That’s the whole video.", type: "video" },
  { src: "photos/08-friends.jpg", caption: "The crew. Studio lights. Easy like this." },
  { src: "photos/09-outdoors.jpg", caption: "Balloons, a mic, and summer hanging around" },
  { src: "videos/clip-4.mp4", poster: "videos/clip-4.jpg", caption: "Walking, laughing, not wanting it to end", type: "video" },
  { src: "photos/10-selfie.jpg", caption: "Crown on. Makeup check. Right before we walked out." },
];
